location              = "centralindia"
resource_group_name   = "rg-static-website"
storage_account_name  = "rishavstoragebucket"
index_file_path       = "./index.html"
error_file_path       = "./404.html"
